version: "3.8"
services:
  bot:
    build: .
    image: fanduel-bot:latest
    container_name: fanduel_bot
    env_file:
      - .env
    environment:
      - TZ=America/New_York
    volumes:
      - .:/app
    command: tail -f /dev/null
