version: "3.9"

services:
  web:
    build: .
    image: fanduel_web
    ports:
      - "8010:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    # no host port published to avoid conflicts; app talks to 'redis' service over the network
