services:
  fanduel_lp:
    build: .
    container_name: fanduel_leaguepicks
    env_file:
      - .env
    ports:
      - "8010:8010"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
