version: "3.9"

services:
  web:
    build: .
    container_name: fanduel-web-1
    environment:
      - TZ=America/Chicago
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8010:8000"
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
  redis:
    image: redis:7-alpine
    container_name: fanduel-redis-1
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
