version: '3.8'

services:
  web:
    container_name: dfs-web
    build: .
    ports:
      - "8010:8000"
    environment:
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ODDS_API_KEY=${ODDS_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - AUTO_MONITORING=${AUTO_MONITORING:-false}
      - AUTO_SWAP_ENABLED=${AUTO_SWAP_ENABLED:-true}
      - MAX_SWAPS_PER_DAY=${MAX_SWAPS_PER_DAY:-3}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/code/app
      - ./data:/code/data
      - ./logs:/code/logs
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dfs-network

  redis:
    container_name: dfs-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dfs-network

volumes:
  redis-data:

networks:
  dfs-network:
    driver: bridge
