version: "3.9"

services:
  web:
    build: .
    image: fanduel_web
    container_name: dfs-web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - "8010:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: dfs-redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
