services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # The command is correctly commented out, allowing the Dockerfile's CMD to run.
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - dfs-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - dfs-network

volumes:
  redis_data:

networks:
  dfs-network:
    driver: bridge
